springdoc:
    api-docs:
        path: /api-docs
        enabled: true
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
    operations-sorter: alpha

logging:
  level:
    root: info                    # 全局保持 INFO，避免系统日志泛滥
    org.example.mylearn: debug  # 针对你的业务逻辑包开启 DEBUG

services: # self defined variable
  sequence-service: sequence-engine

feign:
  client:
    config:
      default:
        connectionTimeout: 3000
        readTimeout: 3000
  httpClient:
    hc5:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      new-sequence:
        failure-rate-threshold: 30
        sliding-window-size: 10
        wait-duration-in-open-state: 10s
        minimum-number-of-calls: 5
        recordExceptions:

management:
  endpoints:
    web:
      exposure:
        include: 'health,info,circuitbreakers,circuitbreaker-events' # 包含断路器相关端点
  endpoint:
    health:
      show-details: always # 在健康检查中显示详细细节

eureka:
  client:
    enabled: false

spring:
  application:
    name: trading-engine
  cloud:
    discovery:
      enabled: false
    openfeign:
      circuitbreaker:
        enabled: false
---
spring:
  config:
    activate:
      on-profile: service
  cloud:
    discovery:
      enabled: true

server:
  port: 8095

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka
    enabled: true
