spring:
  application:
    name: web

logging:
  level:
    root: info                    # 全局保持 INFO，避免系统日志泛滥
    org.example.mylearn: debug  # 针对你的业务逻辑包开启 DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka
    enabled: true
server:
  port: 8080