spring:
  application:
    name: sequence-engine
  cloud:
    sentinel:
      transport:
        dashboard: localhost:9000  #optinal for working without sentinel dashboard
        port: 8719
      eager: true

Logging:
  level:
    root: info
    org.example.mylearn: debug


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: alpha

server:
  port: 8094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka
  instance:
    prefer-ip-address: true

